---

resources:
  - name: git-repository
    type: git
    source: 
      uri: https://github.com/gabsi20/concourse_assignment.git


jobs:
  - name: lint
    plan: 
    - get: git-repository
      trigger: true
    - task: lint
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        inputs:
          - name: git-repository
        run:
          path: sh
          dir: git-repository
          args:
            - "./bin/pipeline/lint"

  - name: unit-test
    plan: 
    - get: git-repository
      trigger: true
    - task: unit-test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        inputs:
          - name: git-repository
        run:
          path: sh
          dir: git-repository
          args: 
            - './bin/pipeline/unit-test'

  - name: acceptance-test
    plan: 
    - get: git-repository
      passed: [unit-test, security-scan, dependency-check, lint]
      trigger: true
    - task: acceptance-test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        inputs:
          - name: git-repository
        run:
          path: sh
          dir: git-repository
          args: 
            - './bin/pipeline/acceptance-test'   
 
  - name: security-scan
    plan: 
    - get: git-repository
      trigger: true
    - task: security-scan
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        inputs:
          - name: git-repository
        run:
          path: sh
          dir: git-repository
          args: 
            - './bin/pipeline/security-scan'  

  - name: dependency-check
    plan: 
    - get: git-repository
      trigger: true
    - task: dependency-check
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        inputs:
          - name: git-repository
        run:
          path: sh
          dir: git-repository
          args: 
            - './bin/pipeline/dependency-check'  

  - name: deploy
    plan:
      - get: git-repository
        passed: [acceptance-test]
        trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: '2.5'
          inputs:
            - name: git-repository
          run:
            path: echo
            args: 
              - 'deploy'  

