---

resources:
  - name: git-repository
    type: git
    source: 
      uri: https://gitlab.com/gabsi20/concourse_assignment.git


jobs: 
  - name: lint
    plan: 
    - get: git-repository
      trigger: true
    - task: lint
      config:
        platform: linux

        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: '2.5'
        
        inputs:
          - name: git-repository
        
        run:
          path: echo
          args: 
            - 'hello world'
  - name: deploy
    plan:
      - get: git-repository
        passed: [lint]
        trigger: true
      - task: deploy
        config:
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli
          
          inputs:
            - name: git-repository

          params:
            HEROKU_EMAIL: ((heroku_email))
            HEROKU_TOKEN: ((heroku_token))

          run:
            path: bash
            dir: git-repository
            args:
              - -exc
              - |
                cat > /root/.netrc <<EOF
                machine git.heroku.com
                  login $HEROKU_EMAIL
                  password $HEROKU_TOKEN
                EOF
                git push https://git.heroku.com/councourse-test-alex.git master:refs/heads/master


